# Generated by Django 3.0.7 on 2020-06-05 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_posts', '0002_auto_20200604_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='cid',
            field=models.CharField(max_length=10, verbose_name='Contact ID'),
        ),
    ]
