# Generated by Django 3.0.7 on 2020-06-05 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_posts', '0003_auto_20200604_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='cid',
        ),
    ]
