# Generated by Django 3.0.6 on 2020-06-02 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('contact', models.IntegerField()),
                ('address', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Detail',
            },
        ),
    ]
